name: Vulnerability scanning
on:
  pull_request:
    types: [opened, synchronize, reopened]
  push:
    branches:
      - "main"
    tags:
      - "v*"

permissions:
  contents: read # This is required for actions/checkout

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
    pip-audit:
      name: pip-audit PyPI vulnerability scanning
      strategy:
        fail-fast: false
      runs-on: ubuntu-latest
      steps:
        - name: Checkout
          uses: actions/checkout@v4

        - name: Install uv
          uses: astral-sh/setup-uv@v5
          with:
            enable-cache: true
            cache-dependency-glob: "uv.lock"

        - name: Install the project and pip
          run: |
            uv sync --locked
            uv pip install pip

        - name: Set up Python
          uses: actions/setup-python@v5
          with:
            python-version-file: "pyproject.toml"

        - uses: pypa/gh-action-pip-audit@v1.1.0
          with:
            ignore-vulns: |
              GHSA-3749-ghw9-m3mg
              # ⬆️ This does not affect us since we do not use `torch.mkldnn_max_pool2d`
              GHSA-887c-mr87-cxwp
              # ⬆️ This does not affect us since we do not use `torch.nn.functional.ctc_loss`
              GHSA-fpwr-67px-3qhx
              # ⬆️ This does not affect us since we do not use tokenization_gpt_neox_japanese.py
              GHSA-4xh5-x5gv-qwph
              # ⬆️ Since we are locking the Python versions as specified in https://github.com/pypa/pip/issues/13522#issuecomment-3354021404
              #    we are not affected by this vulnerability
            vulnerability-service: osv
